class RandomQuotesController < ApplicationController
  def index
    render json: { quote: get_quote }
  end

  private

  def get_quote
    [
      "Que a Força esteja com você",
      "Vou fazer uma oferta que ele não poderá recusar",
      "Elementar, meu caro Watson",
      "Até a vista, baby",
      "Eu sou o rei do mundo",
      "Por que tão sério?",
      "Bazinga!",
      "Isso é Sparta!",
      "Eu vejo pessoas mortas",
      "Houston, temos um problema",
      "A vida encontra um caminho",
      "Com grandes poderes vêm grandes responsabilidades",
      "Você não pode lidar com a verdade",
      "Hakuna Matata",
      "Que comecem os jogos",
      "Eu voltarei",
      "Ninguém coloca Baby num canto",
      "É perigoso ir sozinho",
      "Eu sou seu pai",
      "Continue a nadar",
      "Ao infinito e além",
      "Inverno está chegando",
      "Valar Morghulis",
      "Eu sou inevitável",
      "Wakanda para sempre",
      "Avada Kedavra",
      "Expecto Patronum",
      "A primeira regra do Clube da Luta",
      "Por Asgard!",
      "Eu escolho você",
      "Que a sorte esteja sempre a seu favor",
      "Eu sou Groot",
      "Essa é a minha forma final",
      "Você é um bruxo",
      "Isso vai dar ruim",
      "Correr, Forrest, correr",
      "Say hello to my little friend",
      "Vida longa e próspera",
      "Eu sinto cheiro de vitória",
      "Você está falando comigo?",
      "Por Nárnia!",
      "Não é um bug, é um recurso",
      "Eu faço minhas próprias regras",
      "Isso pertence a um museu",
      "Ninguém manda no meu destino",
      "Prepare-se para problemas",
      "E faça em dobro",
      "Não conte para ninguém",
      "Você não está preparado",
      "Eu sou a noite",
      "Eu sou o Batman",
      "Que os jogos comecem",
      "A verdade está lá fora",
      "O inverno não perdoa",
      "Eu tenho um plano",
      "Isso é só o começo",
      "Nós somos o Flash",
      "Eu acredito em você",
      "Nada é verdade, tudo é permitido",
      "O caos reina",
      "Nós éramos felizes e sabíamos",
      "Essa cidade merece algo melhor",
      "Eu sou a velocidade",
      "Você não é digno",
      "Com licença, princesa",
      "Você subestima meu poder",
      "Eu tenho a vantagem do terreno elevado",
      "É uma armadilha",
      "Execute a Ordem 66",
      "Eu amo você — eu sei",
      "O jogo mudou",
      "Isso é loucura",
      "O multiverso é real",
      "Não pisque",
      "Nós somos Venom",
      "Ele é apenas um garoto",
      "O medo leva à raiva",
      "Eu faço o que quero",
      "Isso foi inevitável",
      "A esperança nunca morre",
      "Grandes homens fazem história",
      "A noite é mais escura antes do amanhecer",
      "Você já esteve dos dois lados",
      "O tempo é relativo",
      "O impossível é só uma opinião",
      "Esse é o caminho",
      "Eu estava esperando por você",
      "O poder vem com sacrifício",
      "A resistência é inútil",
      "Isso não é uma lua",
      "Nós não recuamos",
      "O sonho acabou",
      "O herói cai primeiro",
      "O vilão sempre retorna",
      "Nada acaba realmente",
      "Tudo está conectado",
      "A realidade pode ser decepcionante",
      "Eu nasci para isso",
      "O mundo precisa de heróis",
      "Às vezes os vilões vencem",
      "O medo é a mente assassina",
      "O passado nunca morre",
      "Somos quem escolhemos ser",
      "O destino é escrito por nós",
      "Não confie em ninguém",
      "O jogo nunca termina",
      "Cada escolha tem um preço",
      "A guerra nunca muda",
      "O tempo cobra seu preço",
      "A lenda continua",
      "Nada será como antes",
      "A última esperança",
      "O equilíbrio deve ser mantido",
      "O poder corrompe",
      "A verdade dói",
      "Toda história tem dois lados",
      "A revolução começou",
      "Nada pode nos parar",
      "O futuro é incerto",
      "A queda é inevitável",
      "O ciclo recomeça",
      "O herói reluta",
      "O sacrifício é necessário",
      "A luz ainda existe",
      "O mal nunca descansa",
      "Tudo leva a isso",
      "O destino chama",
      "A escolha é sua",
      "Nada acontece por acaso",
      "O impossível aconteceu",
      "O fim está próximo",
      "O começo de tudo",
      "A jornada importa mais",
      "O legado permanece",
      "O medo controla",
      "A esperança resiste",
      "O tempo acabou",
      "Nada pode nos salvar",
      "A vitória tem um custo",
      "O herói se levanta",
      "O mal observa",
      "A história se repete",
      "O silêncio é ensurdecedor",
      "O caos é inevitável",
      "A verdade liberta",
      "O poder muda tudo",
      "O sacrifício final",
      "O ciclo termina",
      "A lenda nasceu",
      "O mundo observa",
      "A escolha define você",
      "O destino foi selado",
      "O fim é só o começo"
    ].shuffle.pop
  end
end
